name: bohr.io deploy
on: 
  push:
  repository_dispatch:
    types: [bohr-dispatch]
permissions: write-all
jobs:
  deploy:
    name: Deploy on bohr.io
    runs-on: ubuntu-latest
    steps:
      - name: Install NestJs
        run: npm install -g @nestjs/cli
      - name: Install dependecies
        run: yarn
      - name: Build
        run: nest build
      - name: Start Prod
        run: yarn start:prod
